spin_manifest_version = 2

[application]
authors = ["Chris Matteson <chris.matteson@gmail.com>"]
description = ""
name = "spin"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin"

[component.spin]
source = "target/spin.wasm"
exclude_files = ["**/node_modules"]
[component.spin.build]
command = "npm run build"
